### ISSUE TITLE
Implement /delete command

### ISSUE THREAD

**Issue by obitech** [wuest-halle/wuestbot#8]
Users can send `/delete` to the bot to deregister themselves from the bot / database:

- If the user has an entry in the database, delete him and return a success message
- If the user is not in the database, print an error message

**Comment by softbobo** [comment]
we should actually think over if `/delete` is the right name for the command or if `/end` or `/cancel` might be better

**Comment by obitech** [comment]
We could implement the same functionality for all commands, then just advertise `/cancel` in `/help`

**Comment by softbobo** [comment]
> We could implement the same functionality for all commands, then just advertise `/cancel` in `/help`
Yeah right, it is just a minor naming issue. Just wanted to bring it up before we introduce the new feature to the public
